name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the image
        run: docker-compose build

      - name: Run Docker Compose
        run: |
          docker compose up -d

      - name: Containers List
        run: docker ps

      # - name: Bandit
      #   run: |
      #     docker compose run web bandit -r .

      - name: Pytest
        run: |
          docker compose run web poetry run pytest

      - name: Flake8
        run: |
          docker compose run web poetry run flake8 .

      - name: Black Formatter
        uses: psf/black@stable
        id: action_black
        with:
          options: ".
          --skip-string-normalization --exclude=^.*\b(migrations)\b.*$"

      - name: Commit
        if: steps.action_black.outputs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ":art: Format Python code with psf/black"
